include = ["**/*.toml"]

[formatting]
align_entries       = true
align_comments      = true
allowed_blank_lines = 2
array_auto_expand   = true
column_width        = 80
indent_string       = "    "

[schema]
enabled = false

[[rule]]
include = ["**/pyproject.toml"]
[rule.schema]
path = "https://json.schemastore.org/pyproject-toml"
