[formatting]
align_entries = true
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
column_width = 100
indent_string = "    "
trailing_newline = true
reorder_keys = false
